spring:
  application:
    # 服务名称
    name: user-center
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定命名空间
        # namespace:
        # 指定集群名称
        cluster-name: kunming
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sunday
    # >= 6.x: com.mysql.cj.jdbc.Driver
    # <= 5.x: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

# Actuator
management:
  endpoint.health.show-details: always # health
  endpoints:
    web:
      exposure:
        # include: "*"
        include: metrics, health

# info
info:
  app-name: user-center
  author: Coisini
  email: xxx.email

server:
  port: 8081

rocketmq:
  name-server: 127.0.0.1:9876

