spring:
  application:
    # 服务名称
    name: content-center
  main:
    # 允许 feign 同名存在
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 命名空间
        # namespace: 344a899c-05f9-4e40-b2eb-3512928330e6
        # 分组
        # group: TEST_GROUP
        # 集群名称
        # cluster-name: kunming
    sentinel:
      filter:
        # 开启对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定 sentinel 控制台的地址
        dashboard: localhost:8083
      # 控制是否收敛 context。将其配置为 false 即可根据不同的 URL 进行链路限流。
      web-context-unify: false
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sunday
    # >= 6.x: com.mysql.cj.jdbc.Driver
    # <= 5.x: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8010

#user-center:
#  ribbon:
#    # Ribbon负载均衡规则的全路径
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    # 开启饥饿加载
    enabled: true
    # 为哪些RibbonClient开启饥饿加载,多个用 "," 隔开
    clients: user-center

logging:
  level:
    # feign 的日志级别是建立在接口日志级别基础上的
    com.coisini.contentcenter.feignclient.UserCenterFeignClient: debug

# 自定义配置 feign 日志级别
feign:
  sentinel:
    # 为 Feign 整合 Sentinel
    enabled: true
  client:
    config:
      # 调用的微服务名称
      # user-center:
        # loggerLevel: full
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 使用 apache httpclient做请求，而不是默认的 urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

# Actuator
management:
  endpoint.health.show-details: always # health
  endpoints:
    web:
      exposure:
        include: "*"

resttemplate:
  sentinel:
    # @SentinelRestTemplate注解开关
    enabled: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
